"""
angrybird/fire_engine.py

ELMFIRE wrapper for the IGNIS pipeline.

Public surface:
    ElmfireEngine   — core wrapper; takes CycleSnapshot + EnsembleConfig
    ElmfireAdapter  — satisfies FireEngineProtocol; called by orchestrator/runner

The orchestrator calls:
    fire_engine.run(terrain, gp_prior, fire_state, n_members, horizon_min, rng)

ElmfireAdapter.run() translates that into:
    1. Draw GP-scaled perturbation fields from gp_prior + rng
    2. Build CycleSnapshot and EnsembleConfig
    3. Delegate to ElmfireEngine.run()

ElmfireEngine never changes its own interface — all adaptation lives here.

Dependencies: rasterio, numpy (both already in requirements.txt)
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Optional

import numpy as np
import rasterio
from rasterio.transform import from_origin

from .config import (
    GP_CORRELATION_LENGTH_FMC_M,
    GP_CORRELATION_LENGTH_WIND_M,
)
from .gp import draw_gp_scaled_field
from .types import (
    CycleSnapshot,
    EnsembleConfig,
    EnsembleResult,
    GPPrior,
    TerrainData,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Unit conversion helpers
# ---------------------------------------------------------------------------

def _to_elmfire_wind_speed(ws_ms_10m: np.ndarray) -> np.ndarray:
    """
    10-m wind speed in m/s  ->  20-ft wind speed in mph.

    ELMFIRE reads 20-ft winds in mph (WS_AT_10M = .FALSE.).
    Conversion: m/s -> mph via x2.23694; 10m -> 20ft via x1.15
    (neutral-stability log-law approximation, z0 = 0.1 m).
    """
    return ws_ms_10m * 2.23694 * 1.15


def _to_elmfire_fmc(fmc_fraction: np.ndarray) -> np.ndarray:
    """Fuel moisture fraction [0, 1]  ->  percent as expected by ELMFIRE."""
    return fmc_fraction * 100.0


# ---------------------------------------------------------------------------
# Config-file template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
&INPUTS
FUELS_AND_TOPOGRAPHY_DIRECTORY = '{terrain_dir}'
ASP_FILENAME   = 'asp'
CBD_FILENAME   = 'cbd'
CBH_FILENAME   = 'cbh'
CC_FILENAME    = 'cc'
CH_FILENAME    = 'ch'
DEM_FILENAME   = 'dem'
FBFM_FILENAME  = 'fbfm40'
SLP_FILENAME   = 'slp'
ADJ_FILENAME   = 'adj'
PHI_FILENAME   = 'phi'
WEATHER_DIRECTORY       = '{weather_dir}'
WS_FILENAME             = 'ws'
WD_FILENAME             = 'wd'
M1_FILENAME             = 'm1'
M10_FILENAME            = 'm10'
M100_FILENAME           = 'm100'
LH_MOISTURE_CONTENT     = 30.0
LW_MOISTURE_CONTENT     = 60.0
FOLIAR_MOISTURE_CONTENT = 100.0
WS_AT_10M               = .FALSE.
/

&COMPUTATIONAL_DOMAIN
A_SRS                           = '{utm_epsg}'
COMPUTATIONAL_DOMAIN_CELLSIZE   = {cellsize}
COMPUTATIONAL_DOMAIN_XLLCORNER  = {xllcorner}
COMPUTATIONAL_DOMAIN_YLLCORNER  = {yllcorner}
/

&TIME_CONTROL
SIMULATION_TSTART  = 0.0
SIMULATION_TSTOP   = {horizon_s}
SIMULATION_DT      = 5.0
SIMULATION_DTMAX   = 300.0
TARGET_CFL         = 0.4
/

&SIMULATOR
ALLOW_NONBURNABLE_PIXEL_IGNITION = .FALSE.
NUM_IGNITIONS = 1
/

&IGNITION
IGNITION_TYPE = 'POINT'
IGNITION_X    = {ign_x}
IGNITION_Y    = {ign_y}
/

&OUTPUTS
OUTPUTS_DIRECTORY    = '{output_dir}'
DUMP_TIME_OF_ARRIVAL = .TRUE.
DUMP_FLIN            = .TRUE.
DUMP_CROWN_FIRE      = .TRUE.
DUMP_SPREAD_RATE     = .FALSE.
DTDUMP               = {horizon_s}
/
"""


# ---------------------------------------------------------------------------
# Subprocess helper — module-level for ProcessPoolExecutor pickling
# ---------------------------------------------------------------------------

def _run_member(binary: str, member_dir: str, timeout: int) -> None:
    """
    Execute one ELMFIRE instance.
    Raises RuntimeError on non-zero exit so the parent pool can log and continue.
    """
    result = subprocess.run(
        [binary, str(Path(member_dir) / "elmfire.data")],
        cwd=member_dir,
        capture_output=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        snippet = result.stderr.decode(errors="replace")[:600]
        raise RuntimeError(
            f"ELMFIRE exited {result.returncode} in {member_dir}:\n{snippet}"
        )


# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------

class ElmfireEngine:
    """
    Python wrapper around the ELMFIRE Fortran binary.

    Takes CycleSnapshot + EnsembleConfig (perturbations pre-generated by caller).
    Returns EnsembleResult.

    Use ElmfireAdapter to satisfy the orchestrator's FireEngineProtocol.
    """

    def __init__(
        self,
        elmfire_binary: str = "elmfire",
        work_dir: str = "/dev/shm/ignis_elmfire",
        max_workers: int = 8,
        member_timeout_s: int = 120,
    ) -> None:
        preferred = Path(work_dir)
        fallback  = Path("/tmp/ignis_elmfire")
        if str(preferred).startswith("/dev/shm") and not Path("/dev/shm").exists():
            logger.warning("/dev/shm not available; using %s", fallback)
            self.work_dir = fallback
        else:
            self.work_dir = preferred

        self.binary           = elmfire_binary
        self.max_workers      = max_workers
        self.member_timeout_s = member_timeout_s
        self.terrain_dir      = self.work_dir / "terrain"

        self._terrain_written = False
        self._cycle_count     = 0
        self._geo_profile: Optional[dict] = None

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def run(self, snapshot: CycleSnapshot, config: EnsembleConfig) -> EnsembleResult:
        """
        Run N ensemble members through ELMFIRE.

        Parameters
        ----------
        snapshot
            Current cycle state including terrain, GP posterior means, ignition.
        config
            Ensemble size, simulation horizon, and pre-generated perturbation
            fields (float32[N, rows, cols]) in physical units.

        Returns
        -------
        EnsembleResult
            arrival_times[n, r, c] = seconds from sim start.
            Unburned cells = MAX_ARRIVAL = 2 x horizon_s.
        """
        if not self._terrain_written:
            self._write_terrain(snapshot)

        self._cycle_count += 1
        cycle_dir = self.work_dir / f"cycle_{self._cycle_count:03d}"
        cycle_dir.mkdir(parents=True, exist_ok=True)

        N          = config.n_members
        rows, cols = snapshot.terrain.shape
        horizon_s  = config.horizon_hours * 3600.0
        MAX_ARRIVAL = 2.0 * horizon_s

        # --- Write per-member inputs ---
        member_dirs: list[Path] = []
        for n in range(N):
            member_dir  = cycle_dir / f"member_{n:04d}"
            weather_dir = member_dir / "weather"
            output_dir  = member_dir / "outputs"
            weather_dir.mkdir(parents=True, exist_ok=True)
            output_dir.mkdir(parents=True, exist_ok=True)

            self._write_weather(
                weather_dir=weather_dir,
                fmc_fraction=config.perturbations["fmc_1hr"][n],
                ws_ms=config.perturbations["wind_speed"][n],
                wd_deg=config.perturbations["wind_dir"][n],
            )
            self._write_config(
                member_dir=member_dir,
                weather_dir=weather_dir,
                output_dir=output_dir,
                snapshot=snapshot,
                horizon_s=horizon_s,
            )
            member_dirs.append(member_dir)

        # --- Run all members in parallel ---
        failed: set[int] = set()
        with ProcessPoolExecutor(max_workers=self.max_workers) as pool:
            futures = {
                pool.submit(_run_member, self.binary, str(member_dirs[n]), self.member_timeout_s): n
                for n in range(N)
            }
            for future in as_completed(futures):
                n = futures[future]
                exc = future.exception()
                if exc:
                    logger.error("Member %04d failed: %s", n, exc)
                    failed.add(n)

        if failed:
            logger.warning("%d/%d members failed: %s", len(failed), N, sorted(failed)[:10])

        # --- Read arrival times ---
        arrival_times = np.full((N, rows, cols), MAX_ARRIVAL, dtype=np.float32)
        for n, member_dir in enumerate(member_dirs):
            if n in failed:
                continue
            toa = self._read_arrival_time(member_dir / "outputs")
            if toa is None:
                logger.warning("Member %04d produced no time_of_arrival raster", n)
                continue
            toa = np.where(toa < 0,           MAX_ARRIVAL, toa)
            toa = np.where(toa == 0,          MAX_ARRIVAL, toa)
            toa = np.where(toa > MAX_ARRIVAL, MAX_ARRIVAL, toa)
            arrival_times[n] = toa.astype(np.float32)

        # --- Derived fields ---
        burned_mask = arrival_times < (MAX_ARRIVAL * 0.9)
        burn_prob   = burned_mask.mean(axis=0).astype(np.float32)

        masked = np.where(burned_mask, arrival_times, np.nan)
        with np.errstate(invalid="ignore"):
            mean_arrival = np.nanmean(masked, axis=0).astype(np.float32)
        mean_arrival = np.nan_to_num(mean_arrival, nan=MAX_ARRIVAL).astype(np.float32)

        variance = arrival_times.var(axis=0).astype(np.float32)

        return EnsembleResult(
            member_arrival_times  = arrival_times,
            burn_probability      = burn_prob,
            mean_arrival_time     = mean_arrival,
            arrival_time_variance = variance,
            member_fmc_fields     = config.perturbations["fmc_1hr"],
            member_wind_fields    = config.perturbations["wind_speed"],
            n_members             = N,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _write_terrain(self, snapshot: CycleSnapshot) -> None:
        self.terrain_dir.mkdir(parents=True, exist_ok=True)
        t = snapshot.terrain

        base_profile = {
            "driver":    "GTiff",
            "width":     t.shape[1],
            "height":    t.shape[0],
            "count":     1,
            "crs":       snapshot.utm_epsg,
            "transform": from_origin(
                t.origin[0], t.origin[1],
                t.resolution_m, t.resolution_m,
            ),
        }
        self._geo_profile = base_profile.copy()

        int16_profile   = {**base_profile, "dtype": "int16"}
        float32_profile = {**base_profile, "dtype": "float32"}

        int16_layers: dict[str, np.ndarray] = {
            "asp":    t.aspect.astype(np.int16),
            "slp":    t.slope.astype(np.int16),
            "dem":    t.elevation.astype(np.int16),
            "fbfm40": t.fuel_model.astype(np.int16),
            "cc":     np.clip(t.canopy_cover * 100,        0, 32767).astype(np.int16),
            "ch":     np.clip(t.canopy_height * 10,        0, 32767).astype(np.int16),
            "cbh":    np.clip(t.canopy_base_height * 10,   0, 32767).astype(np.int16),
            "cbd":    np.clip(t.canopy_bulk_density * 100, 0, 32767).astype(np.int16),
        }
        for name, data in int16_layers.items():
            self._write_raster(self.terrain_dir / f"{name}.tif", data, int16_profile)

        self._write_raster(
            self.terrain_dir / "adj.tif",
            np.ones(t.shape, dtype=np.float32),
            float32_profile,
        )
        self._write_raster(
            self.terrain_dir / "phi.tif",
            np.ones(t.shape, dtype=np.float32),
            float32_profile,
        )

        self._terrain_written = True
        logger.info("Terrain rasters written to %s", self.terrain_dir)

    def _write_weather(
        self,
        weather_dir: Path,
        fmc_fraction: np.ndarray,
        ws_ms: np.ndarray,
        wd_deg: np.ndarray,
    ) -> None:
        assert self._geo_profile is not None
        profile = {**self._geo_profile, "dtype": "float32"}

        fmc_pct     = _to_elmfire_fmc(fmc_fraction)
        ws_mph_20ft = _to_elmfire_wind_speed(ws_ms)

        for name, data in {
            "m1":   fmc_pct,
            "m10":  fmc_pct * 1.2,
            "m100": fmc_pct * 1.5,
            "ws":   ws_mph_20ft,
            "wd":   wd_deg,
        }.items():
            self._write_raster(weather_dir / f"{name}.tif", data.astype(np.float32), profile)

    def _write_config(
        self,
        member_dir: Path,
        weather_dir: Path,
        output_dir: Path,
        snapshot: CycleSnapshot,
        horizon_s: float,
    ) -> None:
        config_text = _CONFIG_TEMPLATE.format(
            terrain_dir = str(self.terrain_dir),
            weather_dir = str(weather_dir),
            output_dir  = str(output_dir),
            utm_epsg    = snapshot.utm_epsg,
            cellsize    = snapshot.terrain.resolution_m,
            xllcorner   = snapshot.terrain.origin[0],
            yllcorner   = snapshot.terrain.origin[1],
            horizon_s   = horizon_s,
            ign_x       = snapshot.ignition_x,
            ign_y       = snapshot.ignition_y,
        )
        (member_dir / "elmfire.data").write_text(config_text)

    def _read_arrival_time(self, output_dir: Path) -> Optional[np.ndarray]:
        matches = sorted(output_dir.glob("time_of_arrival_*.tif"))
        if not matches:
            return None
        with rasterio.open(matches[-1]) as src:
            return src.read(1).astype(np.float32)

    @staticmethod
    def _write_raster(path: Path, data: np.ndarray, profile: dict) -> None:
        with rasterio.open(path, "w", **profile) as dst:
            dst.write(data, 1)

    def cleanup_cycle(self, cycle_number: Optional[int] = None) -> None:
        n = cycle_number if cycle_number is not None else self._cycle_count
        cycle_dir = self.work_dir / f"cycle_{n:03d}"
        if cycle_dir.exists():
            shutil.rmtree(cycle_dir)

    def cleanup_all(self) -> None:
        if self.work_dir.exists():
            shutil.rmtree(self.work_dir)
        self._terrain_written = False
        self._cycle_count     = 0
        self._geo_profile     = None


# ---------------------------------------------------------------------------
# Adapter — satisfies FireEngineProtocol, called by orchestrator / runner
# ---------------------------------------------------------------------------

class ElmfireAdapter:
    """
    Adapts ElmfireEngine to the FireEngineProtocol expected by IGNISOrchestrator
    and SimulationRunner.

    The orchestrator calls:
        adapter.run(terrain, gp_prior, fire_state, n_members, horizon_min, rng)

    This adapter:
        1. Draws N GP-scaled perturbation fields for FMC, wind speed, wind dir
        2. Constructs CycleSnapshot and EnsembleConfig
        3. Delegates to ElmfireEngine.run()

    Args:
        engine:      ElmfireEngine instance (shared across all cycles)
        utm_epsg:    UTM CRS string, e.g. "EPSG:32610"
        ignition_x:  UTM easting of fire ignition point
        ignition_y:  UTM northing of fire ignition point
    """

    def __init__(
        self,
        engine: ElmfireEngine,
        utm_epsg: str,
        ignition_x: float,
        ignition_y: float,
    ) -> None:
        self._engine     = engine
        self._utm_epsg   = utm_epsg
        self._ignition_x = ignition_x
        self._ignition_y = ignition_y
        self._cycle      = 0

    def run(
        self,
        terrain: TerrainData,
        gp_prior: GPPrior,
        fire_state: np.ndarray,
        n_members: int,
        horizon_min: int,
        rng: Optional[np.random.Generator] = None,
    ) -> EnsembleResult:
        """
        FireEngineProtocol-compliant entry point.

        Perturbation strategy:
          Each member's field = GP posterior mean + GP-scaled correlated noise.
          rng is seeded per-cycle by the orchestrator (PotentialBugs1 section 8)
          so all strategies see an identical ensemble on each cycle.
        """
        self._cycle += 1
        if rng is None:
            rng = np.random.default_rng(self._cycle)

        shape        = terrain.shape
        resolution_m = terrain.resolution_m
        horizon_hrs  = horizon_min / 60.0

        fmc_members = np.stack([
            np.clip(
                gp_prior.fmc_mean + draw_gp_scaled_field(
                    shape, GP_CORRELATION_LENGTH_FMC_M, resolution_m, gp_prior.fmc_variance,
                ),
                0.01, 0.60,
            ).astype(np.float32)
            for _ in range(n_members)
        ])

        ws_members = np.stack([
            np.clip(
                gp_prior.wind_speed_mean + draw_gp_scaled_field(
                    shape, GP_CORRELATION_LENGTH_WIND_M, resolution_m, gp_prior.wind_speed_variance,
                ),
                0.5, 25.0,
            ).astype(np.float32)
            for _ in range(n_members)
        ])

        wd_members = np.stack([
            (
                gp_prior.wind_dir_mean + draw_gp_scaled_field(
                    shape, GP_CORRELATION_LENGTH_WIND_M, resolution_m, gp_prior.wind_dir_variance,
                )
            ).astype(np.float32) % 360.0
            for _ in range(n_members)
        ])

        snapshot = CycleSnapshot(
            terrain           = terrain,
            fire_state        = fire_state,
            fuel_moisture_1hr = gp_prior.fmc_mean,
            wind_speed        = gp_prior.wind_speed_mean,
            wind_direction    = gp_prior.wind_dir_mean,
            utm_epsg          = self._utm_epsg,
            ignition_x        = self._ignition_x,
            ignition_y        = self._ignition_y,
            cycle_number      = self._cycle,
        )

        config = EnsembleConfig(
            n_members     = n_members,
            horizon_hours = horizon_hrs,
            perturbations = {
                "fmc_1hr":    fmc_members,
                "wind_speed": ws_members,
                "wind_dir":   wd_members,
            },
        )

        return self._engine.run(snapshot, config)
